### PR TITLE
fix xyz reader 

### PR DESCRIPTION
**Pull request by NicoRenaud**
Issue describe in #29 
The read_xyz function didn't handle the blank lines properly

Fixed the reader so that only the lines containing atoms are parsed

### CODE REVIEW

**Comment by Rik-Breebaart** [comment]
This does not seem to fix the issue, The issue is that the input of _get-atomic_properties() is 'water.xyz'. The script never goes through the _read_yz_file function.
I think the issue is that from my path the water.xyz is not a file for os.path.isfile()

**Comment by NicoRenaud** [comment]
I guess you do have a water.xyz file in the current working directory right ?

**Comment by Rik-Breebaart** [comment]
Yes I have a water.xyz file in the single_point directory. But as I use vscode I ran from the editor window while the terminal is still in another directory, thus giving the error. When I modified it to 'example/single_point/water.xyz' it worked fine. Sorry.

**Comment by NicoRenaud** [comment]
it forced me to add a few nice checks !

**Pull request merged**
